python:
- 2.7
- 3.8
before_install:
- pip install poetry
install:
- poetry install
script:
- poetry run coverage run -m --source=pyettj pytest ./pyettj/tests
before_deploy:
- poetry build -f sdist
deploy:
  provider: script
  script: poetry publish -r mypypi
  skip_cleanup: true
  on:
    tags: true