language: ruby
dist: xenial
python:
- 3.8
os: linux
before_install:
- sudo apt-get install python3-pip
- pip3 install --upgrade pip
- sudo apt-get update
- sudo apt-get install python3.8
- sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 1
- sudo update-alternatives --config python3
- pip3 install poetry
install:
- poetry install
script:
- poetry run coverage run -m --source=pyettj pytest ./pyettj/tests
before_deploy:
- poetry build -f sdist
deploy:
  provider: script
  script: poetry publish -r mypypi
  on:
    tags: true