python:
- 3.8
os: osx
before_install:
- brew update && brew upgrade pyenv
- pip install poetry
install:
- poetry install
script:
- poetry run coverage run -m --source=pyettj pytest ./pyettj/tests
before_deploy:
- poetry build -f sdist
deploy:
  provider: script
  script: poetry publish -r mypypi
  skip_cleanup: true
  on:
    tags: true